# Generated by Django 4.2.3 on 2023-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_review_review_user_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='active',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='created',
            new_name='Created',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='Avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='Number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
