# Generated by Django 4.2.3 on 2023-09-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_rename_active_watchlist_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
